#!/bin/bash
#SBATCH --job-name=tr_corr2
#SBATCH --account=ar57
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=92160
#SBATCH --cpus-per-task=1
#SBATCH --time=1-00:00:00
#SBATCH --mail-user=xin.zhou1@monash.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --partition=fit
#SBATCH --qos=fitq
#SBATCH --gres=gpu:A100:1 
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err

source activate tsl1
sh /home/xinz/ar57_scratch/xinz/HTSFB_project/baselines/Time-Series-Library/scripts/traffic/Relateformer2.sh
# sh /home/xinz/ar57_scratch/xinz/HTSFB_project/baselines/Time-Series-Library/scripts/traffic/iTransformer.sh
# sh /home/xinz/ar57_scratch/xinz/HTSFB_project/baselines/Time-Series-Library/scripts/traffic/Crossformer.sh
# sh /home/xinz/ar57_scratch/xinz/HTSFB_project/baselines/Time-Series-Library/scripts/traffic/DLinear.sh
# sh /home/xinz/ar57_scratch/xinz/HTSFB_project/baselines/Time-Series-Library/scripts/traffic/Relateformer3.sh
# sh /home/xinz/ar57_scratch/xinz/HTSFB_project/baselines/Time-Series-Library/scripts/traffic/PatchTST.sh